version: 2

project_name: vizdisk

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

dockers:
  - image_templates:
      - "ghcr.io/jimzical/vizdisk:{{ .Tag }}"
      - "ghcr.io/jimzical/vizdisk:latest"
    dockerfile: Dockerfile.release
    goos: linux
    goarch: amd64
    build_flag_templates:
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"

archives:
  - formats:
      - tar.gz
      - binary
    # this name template makes the tar.gz only contain the binary name
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- .Arch }}

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  use: github
  groups:
    - title: Features
      regexp: "^.*feat((\\([\\w\\-]+\\))?):"
      order: 0
    - title: "Bug Fixes"
      regexp: "^.*fix((\\([\\w\\-]+\\))?):"
      order: 1
    - title: Others
      order: 999
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
